gui:
  showIcons: true
customCommands:
  - command: czg
    context: files
    key: c
    output: terminal
  - command: czg ai
    context: files
    key: C
    output: terminal
git:
  branchLogCmd: "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}} --"
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  allBranchesLogCmds:
    - git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all
